import Head from "next/head";
import Link from "next/link";
import connection from '../lib/db';
import Image from "next/image";

export default function Home({ upcomingEvents, latestUncontactedInvites }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div>
          <h2>Próximos eventos</h2>
          <ul>
            { upcomingEvents.map(event => (
              <Link href={`/events/${event.id}`}>
                <h4>{event.name_event}</h4>
                <span>{event.description}</span>
                <div>
                  <div>
                    <span>{event.description}</span>
                    <span>{event.start_date}</span>
                  </div>
                  <div>
                    <Image width={24} height={24} src="/icons/chevron-right-light.png" alt=""/>
                  </div>
                </div>
              </Link>
            ))}
          </ul>
          <h2>Invitados que faltan contactar</h2>
          <ul>
            {latestUncontactedInvites.map(invite => (
              <li key={invite.id}>
                {invite.name} {invite.last_name}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const upcomingEventsQuery = `
    SELECT * FROM evento
    ORDER BY start_date ASC
    LIMIT 2;
  `;

  const latestUncontactedInvitesQuery = `
    SELECT * FROM invitados
    WHERE contactado = 0
    ORDER BY id DESC
    LIMIT 4;
  `;

  try {
    const [upcomingEventsResult] = await connection.query(upcomingEventsQuery);
    const [latestUncontactedInvitesResult] = await connection.query(latestUncontactedInvitesQuery);

    // Convert Date objects to formatted strings
    const formatDate = (date) => {
      if (!date) return null;
      const options = { day: '2-digit', month: 'long', year: 'numeric' };
      return new Date(date).toLocaleDateString('es-ES', options);
    };

    const upcomingEvents = upcomingEventsResult.map(event => ({
      ...event,
      start_date: formatDate(event.start_date),
      end_date: formatDate(event.end_date),
    }));

    const latestUncontactedInvites = latestUncontactedInvitesResult;

    return {
      props: {
        upcomingEvents,
        latestUncontactedInvites,
      },
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: {
        upcomingEvents: [],
        latestUncontactedInvites: [],
      },
    };
  }
}
